spring:
  application:
    name: blog

  datasource:
     url: jdbc:mysql://${RDS_IP}:3306/efubaccount?useSSL=false&useUnicode=true&characterEncoding=UTF
8&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
     username: ${RDS_USERNAME}
     password: ${RDS_PASSWORD}
     driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
     properties:
       hibernate:
         format_sql: true
